services:
  ssh-server:
    build: .
    container_name: my_ssh_project
    ports:
      - "2222:22"
    volumes:
      # สมมติว่าคุณมีไฟล์กุญแจแยกกันในเครื่อง
      - ./key/admin_id_rsa.pub:/home/admin/.ssh/authorized_keys:ro
      - ./key/user_a_id_rsa.pub:/home/user_a/.ssh/authorized_keys:ro
      - ./key/user_b_id_rsa.pub:/home/user_b/.ssh/authorized_keys:ro
    restart: unless-stopped